import { TraitMapping } from '@/types/trait';

export const faceTraits: TraitMapping = {
  // Graceful & Soft (01-10)
  "01": "Gentle Delicate",
  "02": "Youthful Rounded",
  "03": "Elegant Sharp",
  "04": "Mature Refined",
  "05": "Calm Serious",
  "06": "Seductive Half-Lidded",
  "07": "Regal Proud",
  "08": "Cold Sharp Gaze",
  "09": "Exotic Stylized",
  "10": "Innocent Serene",

  // Expressive & Bold (11-20)
  "11": "Mischievous Playful",
  "12": "Confident Bold",
  "13": "Mysterious Subtle",
  "14": "Aloof Distant",
  "15": { name: "Predatory Alluring", description: "Sharp- narrow eyes with an intensely focused- dangerously attractive gaze that tracks movement naturally." },
  "16": "Melancholic Soft",
  "17": "Intimidating Dominant",
  "18": "Cheerful Bright",
  "19": "Uncanny Ethereal",
  "20": "Dignified Matriarchal",

  // Demonic & Altered (21-35)
  "21": "Succubus Smirk",
  "22": { name: "Void-Eyed Stare", description: "Empty- unnerving black sockets that seem to absorb surrounding light, offering a hollow, unnatural stare." },
  "23": "Shattered Mask-Like Face",
  "24": { name: "Vampiric Aristocrat", description: "Strikingly pale- angular features with a perfectly poised, eternally bored expression of eternal superiority." },
  "25": "Third-Eye Insight",
  "26": "Sunken Hollow Beauty",
  "27": "Doll-Like Porcelain Static",
  "28": { name: "Feline-Featured Predator", description: "Subtle cat-like structures with a slightly wider bridge of the nose and split pupils, expressing a coiled anticipation." },
  "29": "Serpentine Elegance",
  "30": "Stitched Maidenly Grace",
  "31": "Crying Black Tears",
  "32": "Glowing Facial Runes",
  "33": "Cracked Marble Skin",
  "34": "Obsidian Lip Lustre",
  "35": "Veiled Mystery",

  // Eldritch & Monstrous Feminine (36-50)
  "36": "Insectoid Compound Eyes",
  "37": "Bleeding Eye Sockets",
  "38": "Multiple Eyes (Symmetric)",
  "39": "Fanged Grace",
  "40": { name: "Web-Veined Cheeks", description: "Translucent skin around the cheeks revealing delicate- darkly-glowing webbed blood vessels underneath." },
  "41": "Star-Lit Pupils",
  "42": "Bioluminescent Freckles",
  "43": "Shadow-Wreathed Visage",
  "44": "Gilded Skull Face-Paint",
  "45": "Lava-Cracked Jawline",
  "46": "Crystal-Encrusted Brow",
  "47": "Ghostly Blue Haze",
  "48": "Naga-Like Scale Patches",
  "49": "Feathered Eyelashes",
  "50": "Abyssal Horror Chic",

  // Extended Demonic & Supernatural (51-99)
  "51": "Twilight-Eyed Sorceress",
  "52": "Void-Touched Ethereal",
  "53": "Crimson-Marked Seductress",
  "54": "Shadow-Veiled Countenance",
  "55": "Obsidian-Jeweled Eyes",
  "56": "Infernal-Crown Face-Paint",
  "57": "Star-Struck Gaze",
  "58": "Lunar-Blessed Features",
  "59": "Cosmic-Rent Face",
  "60": "Shattered-Glass Expression",
  "61": "Marble-Porcelain Beauty",
  "62": "Midnight-Kissed Skin",
  "63": "Phantom-Like Visage",
  "64": "Hellish-Smile Grin",
  "65": "Crown-Marked Brow",
  "66": "Rune-Scarred Cheeks",
  "67": "Jewel-Encrusted Eye Sockets",
  "68": "Bleeding-Rune Forehead",
  "69": "Silver-Veined Temples",
  "70": "Glow-Eyed Predator",
  "71": "Sharp-Featured Elegant",
  "72": "Sadistic-Smile Lips",
  "73": "Twisted-Beauty Contortion",
  "74": "Siren-Like Allure",
  "75": "Devil's-Own Radiance",
  "76": "Ethereal-Demon Hybrid",
  "77": "Glowing-Rune Visage",
  "78": "Skeletal-Feminine Blend",
  "79": "Smoky-Eyed Enchantress",
  "80": "Crystalline-Fractured Face",
  "81": "Black-Tear Streaked",
  "82": "Bioluminescent-Marked",
  "83": "Ancient-Evil Presence",
  "84": "Angelic-Demonic Blend",
  "85": "Serpent-Tongued Visage",
  "86": "Web-Marked Cheekbones",
  "87": "Moth-Winged Eye Makeup",
  "88": "Dripping-Gold Ornament",
  "89": "Curse-Marked Forehead",
  "90": "Twilight-Split Face",
  "91": "Endless-Void Stare",
  "92": "Flame-Kissed Beauty",
  "93": "Ink-Marked Elegant",
  "94": "Phantom-Pale Features",
  "95": "Demonic-Precious Hybrid",
  "96": "Shadow-Crowned Expression",
  "97": "Star-Born Deity Face",
  "98": "Transcendent-Terror Visage",
  "99": "Ultimate-Succubus Perfection"
};