import { TraitMapping } from '@/types/trait';

export const hairTraits: TraitMapping = {
  // Short & Cropped (01-05)
  "01": "Curly Hair",
  "02": "Very Short Crop",
  "03": "Short Sleek",
  "04": "Short Layered",
  "05": "Chin-Length Bob",

  // Medium & Standard (06-08)
  "06": "Medium Straight",
  "07": "Medium Layered",
  "08": "Long Straight",

  // Long & Elegant (09-12)
  "09": "Long Flowing",
  "10": "Very Long Waist-Length",
  "11": "Wavy Mid-Length",
  "12": { name: "Wavy Long", description: "Thick-lustrous waves heavily cascading down the back in an elegant but untamed manner." },

  // Textured & Tied (13-18)
  "13": "Curly Medium",
  "14": "Tight Curls Long",
  "15": "High Ponytail",
  "16": "Twin Tails",
  "17": "Braided Single",
  "18": "Multiple Braids",

  // Stylized & Sharp (19-25)
  "19": { name: "Asymmetrical Cut", description: "A jagged-daring haircut heavily trimmed on one side while hanging dramatically long on the other." },
  "20": "Gravity-Defying Flow",
  "21": "Side-Swept Undercut",
  "22": "Sharp Spiked Mullet",
  "23": "Hime Cut with Bangs",
  "24": { name: "Wolf Cut", description: "A highly textured-choppy layered cut merging a shag and mullet, framing the face with sharp edges." },
  "25": "Shaved with Sigil Patterns",

  // Gothic & Aristocratic (26-35)
  "26": "Victorian Updo",
  "27": "Twin Buns (Ox Horns)",
  "28": "Gothic Lolita Ringlets",
  "29": "Widow's Peak Slickback",
  "30": "Messy 'Just Risen' Bedhead",
  "31": "Braided Crown",
  "32": "Low Hanging Chignon",
  "33": "Covering One Eye",
  "34": "Bouffant with Ribbons",
  "35": "Wet Look (Drenched)",

  // Supernatural & Demonic (36-50)
  "36": { name: "Living Snake Tresses", description: "Hair completely replaced by wriggling-independently moving serpents that periodically hiss and flare." },
  "37": "Whispy Smoke Hair",
  "38": "Liquid Fire Strands",
  "39": "Floating Ethereal Hair",
  "40": { name: "Tentacle-like Tendrils", description: "Thick-fleshy-cephalopod-esque appendages replacing normal hair strands continuously shifting on their own." },
  "41": "Crystaline Shards Hair",
  "42": "Void Black Mist",
  "43": "Spider-Web Silk Hair",
  "44": "Bioluminescent Fiber-Optic",
  "45": "Metallic Wire Strands",
  "46": "Feathered Plumage Hair",
  "47": "Thorned Vine Wraps",
  "48": "Bleeding Tipped Ends",
  "49": "Star-Field Galaxy Hair",
  "50": "Ragged Tattered Strips",
  // Modern & High-Fashion (51-65)
  "51": "Pixie Cut-Micro Bangs",
  "52": "Blunt Cut-Bob with Straight Fringe",
  "53": "Tousled-Shaggy Layers",
  "54": "Side-Parted-Sleek Glamour Waves",
  "55": "Messy-High Bun-Loose Strands",
  "56": "Pinned-Back-Elegant Half-Updo",
  "57": "Soft-Tapered Nape-Layered Top",
  "58": "Voluminous-Disco Curls",
  "59": "Flipped-Out-Ends 90s Style",
  "60": { name: "Butterfly Cut", description: "Feathered-long-layers that create heavy-volume and movement-resembling wings." },
  "61": "Slicked-Back-Wet Texture-High Shine",
  "62": "Deep-Side Sweep-Heavy Fringe",
  "63": "French-Braid-Low-Side Tail",
  "64": "Waterfall-Braid-Flowing Waves",
  "65": { name: "Jellyfish Cut", description: "A blunt-outer-bob-layer with long-thin-under-strands-mimicking tentacles." },

  // Structural & Cultural (66-75)
  "66": "Top-Knot-Shaved-Sides",
  "67": "Braided-Fishtail-Shoulder-Drape",
  "68": "Spiral-Perm-Extreme Volume",
  "69": "Curtain-Bangs-Face-Framing-Layers",
  "70": "Space-Buns-Loose-Bottom-Strands",
  "71": { name: "Layered Shag", description: "A multi-level-choppy-cut with messy-texture and sharp-tapered-ends." },
  "72": "Tight-Low-Ponytail-Center-Part",
  "73": "Bohemian-Loose-Braids-with-Flowers",
  "74": "Super-Long-Braided-Rope-Tail",
  "75": "Short-Spiky-Punk-Cut",

  // Extended Supernatural & Demonic (76-99)
  "76": "Obsidian-Wave Cascade",
  "77": "Flame-Tipped Ends",
  "78": "Void-Black Tendrils",
  "79": "Shadow-Silk Strands",
  "80": "Moonlit-Silver Cascade",
  "81": "Crimson-Fire Gradient",
  "82": "Storm-Cloud Texture",
  "83": "Ethereal-Whisper Wisps",
  "84": "Ink-Dipped Ombre",
  "85": "Glowing-Edge Boundaries",
  "86": "Rune-Traced Braids",
  "87": "Curse-Marked Locks",
  "88": "Twilight-Gradient Fade",
  "89": "Aurora-Borealis Strands",
  "90": "Deep-Sea Teal Waves",
  "91": "Infernal-Orange Glow",
  "92": "Void-Silk Waterfall",
  "93": "Crown-Jewel Ornated",
  "94": "Phantom-White Strands",
  "95": "Bleeding-Noir Ombre",
  "96": "Shadow-Dance Movement",
  "97": "Demonic-Gorgeous Perfection",
  "98": "Transcendent-Hair Flow",
  "99": "Ultimate-Succubus Tresses"
};