export const poseTraits: Record<string, string> = {
  // Graceful & Elegant (01-10)
  "01": "Elegant Standing- Calm Expression",
  "02": "Statuesque Pose- Serene Smile",
  "03": "Head Tilted Back- Blissful Look",
  "04": "Sitting Gracefully- Aloof Gaze",
  "05": "One Hand on Hip- Confident Smirk",
  "06": "Kneeling Elegantly- Gentle Sorrow",
  "07": "Arms Crossed- Judging Stare",
  "08": "Looking Over Shoulder- Playful Wink",
  "09": "Delicate Hand to Face- Melancholic",
  "10": "Swaying Hip Pose- Seductive Smile",

  // Predatory & Intense (11-20)
  "11": "Crouched Low- Predatory Intensity",
  "12": "Leaning Forward- Fierce Snarl",
  "13": "Sharp Turn- Intimidating Gaze",
  "14": "Hand Reaching Forward- Dominant",
  "15": "Lowered Head- Menacing Shadowed Eyes",
  "16": "Arching Back- Wild Untamed Energy",
  "17": "Feral Squat- Hunger in Eyes",
  "18": "Looming Forward- Sinister Grin",
  "19": "Ready to Pounce- Cold Determination",
  "20": "Tense Stance- Boiling Rage",

  // Supernatural & Ethereal (21-30)
  "21": "Floating Mid-Air- Dreamy Trance",
  "22": "Levitating- Expressionless Void",
  "23": "Twisting Torso- Uncanny Contortion",
  "24": "Drifting Sideways- Ghostly Serenity",
  "25": "Upside Down Float- Mischievous Grin",
  "26": "Sprawled in Void- Bored Divinity",
  "27": "T-Pose Variation- Divine Radiance",
  "28": "Coiled Position- Slithering Grace",
  "29": "Back to Camera- Head Turned 180 Degrees",
  "30": "Fading into Shadows- Sad Departure",

  // Alluring & Succubus-Themed (31-40)
  "31": "Lying Down- Alluring Invitation",
  "32": "Biting Lip- Intense Desire",
  "33": "One Leg Raised- Playful Tease",
  "34": "Hands Behind Head- Relaxed Confidence",
  "35": "Self-Embrace- Ecstatic Pleasure",
  "36": "Stretching- Lazy Morning Vibe",
  "37": "Whispering Gesture- Secretive Smirk",
  "38": "Languid Recline- Royal Boredom",
  "39": "Bending Forward- Intense Focus",
  "40": "Pulling Hair Back- Challenging Stare",

  // Chaotic & Demonic (41-50)
  "41": "Laughing Maniacally- Wide Stance",
  "42": "Gripping Face- Mental Anguish",
  "43": "Bleeding Eyes- Stoic Silence",
  "44": "Worshiping Gesture- Religious Ecstasy",
  "45": "Sitting on Throne- Absolute Dominance",
  "46": "Clawing at Chest- Heartbroken Rage",
  "47": "Spitting Blood- Defiant Gaze",
  "48": "Covering Mouth- Muffled Laughter",
  "49": "Looking Down- Pitiful Contempt",
  "50": "Ascending- Transcendental Calm",
  "51": "Hero-Landing-Crouch-One-Knee-Down",
  "52": "Walking-Forward-Determined-Gaze",
  "53": "Back-Arched-Looking-at-Sky-Arms-Spread",
  "54": "Side-Profile-Sharp-Turn-to-Camera",
  "55": "Leaning-Against-Invisible-Wall-Cool-Expression",
  "56": "Mid-Spin-Flowing-Hair-Dynamic-Motion",
  "57": "Squatting-on-Heels-Looking-Up-Curiously",
  "58": "Falling-Backwards-Peaceful-Face",
  "59": "Running-Towards-Viewer-Intense-Focus",
  "60": "Hand-to-Forehead-Dramatic-Gasp",
  "61": "Pointing-Directly-at-Viewer-Mocking-Smile",
  "62": "Holding-Invisible-Sword-Combat-Stance",
  "63": "Defensive-Crossed-Arms-Shielding-Face",
  "64": "Staggering-Backwards-Fearful-Gaze",
  "65": "Kneeling-One-Arm-Raised-Pleading",

  // --- High-Fashion & Editorial (66-80) ---
  "66": "Model-Walk-Sharp-Angle-Hips",
  "67": "Seated-Crossed-Legs-Hand-Under-Chin",
  "68": "Arms-Raised-Adjusting-Horns",
  "69": "Crouched-Side-View-Head-Turned-Sharp",
  "70": "Shoulders-Slumped-Dejected-Expression",
  "71": "Prone-Position-Propped-on-Elbows",
  "72": "Sitting-with-Knees-to-Chest-Deep-Thought",
  "73": "Wide-Legged-Power-Stance-Fists-Clenched",
  "74": "Touching-Lips-with-Finger-Lost-in-Thought",
  "75": "Bending-Sideways-Checking-Heels",
  "76": "Diva-Pose-Back-Hand-on-Forehead",
  "77": "Floating-Curled-in-Fetal-Position",
  "78": "Tiptoe-Stance-Reaching-for-Stars",
  "79": "Leaning-Back-on-Hands-Casual-Gaze",
  "80": "Symmetrical-Pose-Hands-Together-in-Prayer",

  // --- Psychological & Uncanny (81-90) ---
  "81": "Head-Tilted-90-Degrees-Creepy-Smile",
  "82": "Twisting-Body-Away-Face-Glancing-Back",
  "83": "Hands-Covering-Eyes-Smiling-Mouth-Visible",
  "84": "Hunched-Over-Clutching-Stomach-Pain",
  "85": "Puppet-Like-Stance-Limp-Limbs",
  "86": "Scratching-Neck-Nervous-Twitch",
  "87": "Wide-Eyed-Stare-Frozen-in-Shock",
  "88": "Gently-Pulling-Cheek-Mischievous-Look",
  "89": "Pointing-to-Head-Genius-Smirk",
  "90": "Lying-on-Back-Staring-into-Infinity",

  // --- Action-Reaction & Combat (91-100) ---
  "91": "Mid-Jump-Legs-Tucked-High-Impact",
  "92": "Sliding-on-Ground-Dust-Cloud-Imagined",
  "93": "Blocking-Light-with-Hand-Squinting",
  "94": "Wiping-Mouth-After-Battle-Exhausted",
  "95": "Summoning-Gesture-Hand-Glow-Imagined",
  "96": "Looking-Down-at-Hands-Identity-Crisis",
  "97": "Resting-Chin-on-Shoulder-Secret-Gaze",
  "98": "Violent-Shudder-Body-Tense",
  "99": "Graceful-Bow-Curtsy-Demonic-Elegance",
};