export const skinTraits: Record<string, string> = {
  // Humanoid & Natural Tones (01-10)
  "01": "Pale White",
  "02": "Porcelain White",
  "03": "Pale Peach",
  "04": "Light Pink",
  "05": "Warm Ivory",
  "06": "Warm Tan",
  "07": "Golden Tan",
  "08": "Light Brown",
  "09": "Medium Brown",
  "10": "Deep Brown",

  // Grayscale & Dark Tones (11-15)
  "11": "Deep Black",
  "12": "Ash Gray",
  "13": "Silver Gray",
  "14": "Charcoal",
  "15": "Deep Obsidian",

  // Earthy & Elemental (16-20)
  "16": "Olive",
  "17": "Jade Green",
  "18": "Emerald Green",
  "19": "Deep Forest Green",
  "20": "Sulfur Yellow",

  // Cold & Aquatic (21-25)
  "21": "Teal",
  "22": "Deep Blue",
  "23": "Midnight Blue",
  "24": "Ice Cold Cyan",
  "25": "Bioluminescent Blue",

  // Hellish & Infernal (26-30)
  "26": "Violet",
  "27": "Crimson Red",
  "28": "Blood Maroon",
  "29": "Magma Orange",
  "30": "Burnt Umber",

  // Exotic & Supernatural (31-40)
  "31": "Lavender",
  "32": "Royal Purple",
  "33": "Toxic Neon Green",
  "34": "Bubblegum Pink",
  "35": "Iridescent Pearl",
  "36": "Golden Leaf",
  "37": "Bronze Metallic",
  "38": "Chrome Silver",
  "39": "Ghostly Translucent",
  "40": "Cosmic Stardust",

  // Extended Demonic & Supernatural (41-99)
  "41": "Twilight Purple",
  "42": "Void-Touched Gray",
  "43": "Obsidian Shimmer",
  "44": "Infernal Red",
  "45": "Hellfire Orange",
  "46": "Shadow-Black Satin",
  "47": "Moonlit Blue",
  "48": "Starfall Silver",
  "49": "Phantom White",
  "50": "Spectral Green",
  "51": "Aurora-Borealis Mix",
  "52": "Twilight Indigo",
  "53": "Midnight Plum",
  "54": "Cursed Bronze",
  "55": "Ethereal Pearl",
  "56": "Divine Gold",
  "57": "Shadow Maroon",
  "58": "Blood Orange",
  "59": "Ember Red",
  "60": "Void Purple",
  "61": "Cosmic Black",
  "62": "Star-Lit Cyan",
  "63": "Twilight Pink",
  "64": "Demon Scarlet",
  "65": "Infernal Copper",
  "66": "Shadow-Silver Blend",
  "67": "Ethereal Lavender",
  "68": "Mystical Teal",
  "69": "Arcane Violet",
  "70": "Demonic Jade",
  "71": "Hellish Amber",
  "72": "Phantom Gray",
  "73": "Glowing Magenta",
  "74": "Dark Sapphire",
  "75": "Cursed Emerald",
  "76": "Void-Touched Rose",
  "77": "Infernal Gold",
  "78": "Shadow Bronze",
  "79": "Twilight Fuchsia",
  "80": "Spectral Blue",
  "81": "Demonic Pink",
  "82": "Hellish Purple",
  "83": "Ethereal Mint",
  "84": "Cosmic Coral",
  "85": "Obsidian Rose",
  "86": "Midnight Teal",
  "87": "Aurora Purple",
  "88": "Infernal Scarlet",
  "89": "Shadow Platinum",
  "90": "Divine Crimson",
  "91": "Phantom Opal",
  "92": "Cursed Silver",
  "93": "Void Magenta",
  "94": "Twilight Gold",
  "95": "Demonic Perfection",
  "96": "Infernal Elegance",
  "97": "Transcendent Radiance",
  "98": "Ultimate Demon Skin",
  "99": "Succubus-Divine Essence"
};